services:
  - type: web
    name: netflix-cookie-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: REQUIRED_CHANNEL_USERNAME
        sync: false
      - key: CHANNEL_ID
        sync: false
    plan: free
    region: oregon
